"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
exports.__esModule = true;
exports.JubJub__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [],
        name: "COFACTOR",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
        ],
        stateMutability: "view",
        type: "function"
    },
    {
        inputs: [],
        name: "JUBJUB_A",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
        ],
        stateMutability: "view",
        type: "function"
    },
    {
        inputs: [],
        name: "JUBJUB_D",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
        ],
        stateMutability: "view",
        type: "function"
    },
    {
        inputs: [],
        name: "L",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
        ],
        stateMutability: "view",
        type: "function"
    },
    {
        inputs: [],
        name: "Q",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
        ],
        stateMutability: "view",
        type: "function"
    },
];
var _bytecode = "0x61011c61003a600b82828239805160001a60731461002d57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe7300000000000000000000000000000000000000003014608060405260043610606a5760003560e01c8063e493ef8c116055578063e493ef8c1460ae578063eb83733c1460d4578063f7c2d5741460dd57600080fd5b80639357361e14606f5780639f13f76d146088575b600080fd5b6076600881565b60405190815260200160405180910390f35b60767f060c89ce5c263405370a08b6d0302b0bab3eedb83920ee0a677297dc392126f181565b60767f30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f000000181565b6076620292fc81565b6076620292f88156fea26469706673582212204b5389195a5a4573abf529709835cd783f99f4429b875f5bf058d1a93395c06464736f6c634300080c0033";
var JubJub__factory = /** @class */ (function (_super) {
    __extends(JubJub__factory, _super);
    function JubJub__factory() {
        var args = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            args[_i] = arguments[_i];
        }
        var _this = this;
        if (args.length === 1) {
            _this = _super.call(this, _abi, _bytecode, args[0]) || this;
        }
        else {
            _this = _super.apply(this, args) || this;
        }
        return _this;
    }
    JubJub__factory.prototype.deploy = function (overrides) {
        return _super.prototype.deploy.call(this, overrides || {});
    };
    JubJub__factory.prototype.getDeployTransaction = function (overrides) {
        return _super.prototype.getDeployTransaction.call(this, overrides || {});
    };
    JubJub__factory.prototype.attach = function (address) {
        return _super.prototype.attach.call(this, address);
    };
    JubJub__factory.prototype.connect = function (signer) {
        return _super.prototype.connect.call(this, signer);
    };
    JubJub__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    JubJub__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    JubJub__factory.bytecode = _bytecode;
    JubJub__factory.abi = _abi;
    return JubJub__factory;
}(ethers_1.ContractFactory));
exports.JubJub__factory = JubJub__factory;
