"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
exports.__esModule = true;
exports.MockOracle__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_price",
                type: "uint256"
            },
        ],
        stateMutability: "nonpayable",
        type: "constructor"
    },
    {
        inputs: [],
        name: "getEthPrice",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
        ],
        stateMutability: "view",
        type: "function"
    },
    {
        inputs: [],
        name: "price",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
        ],
        stateMutability: "view",
        type: "function"
    },
];
var _bytecode = "0x60a060405234801561001057600080fd5b5060405161013538038061013583398101604081905261002f91610037565b608052610050565b60006020828403121561004957600080fd5b5051919050565b60805160c761006e6000396000818160390152606f015260c76000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c806367c9b017146037578063a035b1fe14606b575b600080fd5b7f00000000000000000000000000000000000000000000000000000000000000005b60405190815260200160405180910390f35b60597f00000000000000000000000000000000000000000000000000000000000000008156fea264697066735822122073d1d407c468c81c2864bcd6fe6b2d5161ca2841b1ce88e02419141bbe292e6764736f6c634300080c0033";
var MockOracle__factory = /** @class */ (function (_super) {
    __extends(MockOracle__factory, _super);
    function MockOracle__factory() {
        var args = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            args[_i] = arguments[_i];
        }
        var _this = this;
        if (args.length === 1) {
            _this = _super.call(this, _abi, _bytecode, args[0]) || this;
        }
        else {
            _this = _super.apply(this, args) || this;
        }
        return _this;
    }
    MockOracle__factory.prototype.deploy = function (_price, overrides) {
        return _super.prototype.deploy.call(this, _price, overrides || {});
    };
    MockOracle__factory.prototype.getDeployTransaction = function (_price, overrides) {
        return _super.prototype.getDeployTransaction.call(this, _price, overrides || {});
    };
    MockOracle__factory.prototype.attach = function (address) {
        return _super.prototype.attach.call(this, address);
    };
    MockOracle__factory.prototype.connect = function (signer) {
        return _super.prototype.connect.call(this, signer);
    };
    MockOracle__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    MockOracle__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    MockOracle__factory.bytecode = _bytecode;
    MockOracle__factory.abi = _abi;
    return MockOracle__factory;
}(ethers_1.ContractFactory));
exports.MockOracle__factory = MockOracle__factory;
