"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
exports.__esModule = true;
exports.Oracle__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [
            {
                internalType: "contract AggregatorV3Interface",
                name: "_priceFeed",
                type: "address"
            },
        ],
        stateMutability: "nonpayable",
        type: "constructor"
    },
    {
        inputs: [],
        name: "getEthPrice",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
        ],
        stateMutability: "view",
        type: "function"
    },
];
var _bytecode = "0x60a060405234801561001057600080fd5b5060405161021638038061021683398101604081905261002f91610040565b6001600160a01b0316608052610070565b60006020828403121561005257600080fd5b81516001600160a01b038116811461006957600080fd5b9392505050565b60805161018c61008a6000396000604f015261018c6000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c806367c9b01714610030575b600080fd5b61003861004a565b60405190815260200160405180910390f35b6000807f000000000000000000000000000000000000000000000000000000000000000073ffffffffffffffffffffffffffffffffffffffff1663feaf968c6040518163ffffffff1660e01b815260040160a060405180830381865afa1580156100b8573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906100dc9190610106565b509195945050505050565b805169ffffffffffffffffffff8116811461010157600080fd5b919050565b600080600080600060a0868803121561011e57600080fd5b610127866100e7565b945060208601519350604086015192506060860151915061014a608087016100e7565b9050929550929590935056fea2646970667358221220c2fcb8c3d762c88fca74be04f76027e91175bed063469c8c145e981cb1f8aafd64736f6c634300080c0033";
var Oracle__factory = /** @class */ (function (_super) {
    __extends(Oracle__factory, _super);
    function Oracle__factory() {
        var args = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            args[_i] = arguments[_i];
        }
        var _this = this;
        if (args.length === 1) {
            _this = _super.call(this, _abi, _bytecode, args[0]) || this;
        }
        else {
            _this = _super.apply(this, args) || this;
        }
        return _this;
    }
    Oracle__factory.prototype.deploy = function (_priceFeed, overrides) {
        return _super.prototype.deploy.call(this, _priceFeed, overrides || {});
    };
    Oracle__factory.prototype.getDeployTransaction = function (_priceFeed, overrides) {
        return _super.prototype.getDeployTransaction.call(this, _priceFeed, overrides || {});
    };
    Oracle__factory.prototype.attach = function (address) {
        return _super.prototype.attach.call(this, address);
    };
    Oracle__factory.prototype.connect = function (signer) {
        return _super.prototype.connect.call(this, signer);
    };
    Oracle__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    Oracle__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    Oracle__factory.bytecode = _bytecode;
    Oracle__factory.abi = _abi;
    return Oracle__factory;
}(ethers_1.ContractFactory));
exports.Oracle__factory = Oracle__factory;
